### ISSUE TITLE
Making project goal more explicit

### ISSUE THREAD

**Issue by swester3** [pi4-uiuc/TeamTwo#1]
We need to figure out exactly what we are going to be analyzing, and what data (explicitly) we are going to need.

**Comment by wlinz** [comment]
And then update the readme file appropriately.

**Comment by jtkelm2** [comment]
Are we all in agreement that it feels like we're trying to row a cruise ship with paddles in this project and there's no way we can achieve our goal in seven days at this rate?

**Comment by swester3** [comment]
Yes! Definitely.
