### ISSUE TITLE
Meaning of min_plantingdensity and max_plantingdensity in species table

### ISSUE THREAD

**Issue by wlinz** [pi4-uiuc/TeamTwo#10]
In looking through the species table, we observed that there is a min planting density and a max planting density associated with each species. Are these based on recommendations for planting? Direct observations? Also, many species have a min and max planting density of 0 - does this mean data is unavailable?

**Comment by dlebauer** [comment]
those are all in the species table, and are generic recommendations from
the USDA Plants Database.

**Comment by wlinz** [comment]
Thanks.
