### ISSUE TITLE
Not enough meaningful planting density data

### ISSUE THREAD

**Issue by swester3** [pi4-uiuc/TeamTwo#11]
After looking through the density data, it looks like each plant species has a fixed plant density value recorded. Thus we can't investigate how planting density affects the yield of the crop, as we originally intended. It looks like we need to transition to what Justin has been working on, unless we can figure out a way to access more meaningful density data.

**Comment by dlebauer** [comment]
@swester3 could you please paste the code that you used to come to this conclusion? That way I can confirm if it is the code or the database that is lacking.

**Comment by swester3** [comment]
We used these two pieces of code:
TeamTwo/src/DataCollection.R
TeamTwo/src/DataMerging.R
